stages:
  - build
  - nuget

build:
  stage: build
  script:
  - cd DotNet-Mono
  - echo "Restoring NuGet Packages..."
  - '".nuget/nuget.exe" restore "Sbatman.Networking.sln" -source "https://www.nuget.org/api/v2/"'
  - echo "Release build..."
  - '"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet "Sbatman.Networking.sln"'
  - echo "Debug build..."
  - '"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Debug /verbosity:quiet "Sbatman.Networking.sln"'
  artifacts:
    paths:
    - DotNet-Mono/bin/Release
    - DotNet-Mono/bin/Debug

nuget:
  stage: nuget
  script:
  - cd DotNet-Mono
  - '".nuget/nuget.exe" pack "Sbatman.Networking.csproj"'
  - '".nuget/nuget.exe" push *'
  only:
  - tags